# GitHub Actionsの設定ファイルをLintする

name: actionlint

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**

jobs:
  run-actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.43.2
      - uses: suzuki-shunsuke/github-action-actionlint@v0.1.5
